language: python
python:
  - "3.5"
env:
  - DJANGO_VERSION=1.10
install:
  - pip install -r requirements.txt
  - pip install -q Django==$DJANGO_VERSION
  - python setup.py -q install
# command to run tests
script: python manage.py test mail
